config/routes.rb
Rails.application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/', to: 'sites#load', constraints: { subdomain: /.+/ }, via: [:get, :post, :put, :patch, :delete]
  root 'sites#index'
  get '/logout', to: 'sessions#destroy'
  get '/auth/dropbox', to: 'sessions#new'
  match '/*req', to: 'sites#load', constraints: { subdomain: /.+/ }, via: [:get, :post, :put, :patch, :delete]
  get '/about', to: 'pages#about'
  get '/source', to: 'pages#source'
  get '/pricing', to: 'pages#pricing'
  get '/admin', to: 'pages#admin'
  get '/webhook', to: 'webhook#challenge'
  post '/webhook', to: 'webhook#post'
  post "/versions/:id/revert", to: "versions#revert", as: "revert_version"
  resources :sites, path: '' 
end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :user, :foreign_key => :uid, :primary_key => :uid
  has_paper_trail
  validates :subdomain, uniqueness: { case_sensititve: false }
  validates :name, presence: true
  validates :domain, uniqueness: { case_sensititve: false, allow_blank: true }
  validate :domain_isnt_updog
  validate :domain_is_a_subdomain
  validate :user_has_less_than_5_sites
  before_validation :namify

  def to_param
      "#{id}-#{name.parameterize}"
  end 

  def creator
    User.find_by( uid: self.uid )
  end

  def content client, env 
    if env['REQUEST_URI'][-1] == "/"
      path = env['PATH_INFO'] + "/index.html"
    else
      path = env['PATH_INFO']
    end
    Rails.cache.fetch("#{cache_key}/#{path}", expires_in: 30.seconds) do
      begin 
	if path != '/'
	  client.get_file( self.name + '/_site/' + path ).html_safe
	else
	  client.get_file( self.name + '/_site/index.html' ).html_safe
	end
      rescue
	if path != '/'
	  client.get_file( self.name + path ).html_safe
	else
	  client.get_file( self.name + '/index.html' ).html_safe
	end
      end
    end
  end

  def user_has_less_than_5_sites
    if self.user && self.user.sites.length > 4 
      errors.add(:number_of_sites, "can't be greater than 5")
    end
  end

  def domain_isnt_updog
    if self.domain =~ /tyrant\.gq/
      errors.add(:domain, "can't contain tyrant.gq")
    end
  end

  def domain_is_a_subdomain
    if self.domain && self.domain != "" && self.domain !~ /\w+\.\w+\.\w+/
      errors.add(:domain, "must have a subdomain like www.")
    end
  end

  def link
    if self.domain && self.domain != ""
      self.domain
    else
      self.subdomain
    end
  end

  private
   def  namify
    self.name.downcase!
    self.name = self.name.gsub(/[^\w+]/,'-')
    self.name = self.name.gsub(/-+$/,'')
    self.name = self.name.gsub(/^-+/,'')
    self.subdomain = self.name + '.tyrant.gq'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :sites, :foreign_key => :uid, :primary_key => :uid
  def self.create_with_omniauth( email, uid, name )
	create! do |user|
	  user.email = email
	  user.provider = 'dropbox'
	  user.uid = uid
	  user.name = name
	end
    end
end

app/controllers/application_controller.rb
require 'dropbox_sdk'
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def get_client at
    return DropboxClient.new(at)
  end

  def current_user
    User.find_by( access_token: session['access_token'] )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

  def pricing
  end

  def source
  end
  
  def admin
    if current_user && current_user.id == 1
      @users = User.all
      @sites = Site.all
    else
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
require 'dropbox_sdk'
class SessionsController < ApplicationController
  def get_auth
    redirect_uri = ENV['db_callback']
    flow = DropboxOAuth2Flow.new( ENV['db_key'], ENV['db_secret'], redirect_uri, session, :dropbox_auth_csrf_token)
  end
  def new
     auth_url = get_auth.start
     redirect_to auth_url
  end
  def index
    if session['access_token'] != ''
      @user = get_dropbox_client.account_info['display_name']
    end
  end
  def create     
    code = params[:code]
    begin
      access_token, user_id, url_state = get_auth.finish(params)
    rescue Exception
    end
    session['access_token'] = access_token
    @db = get_client access_token
    name = @db.account_info['display_name']
    email = @db.account_info['email']
    uid = @db.account_info['uid']
    user = User.find_by_provider_and_uid('dropbox', user_id) || User.create_with_omniauth(email, uid, name)     
    session[:user_id] = uid
    session[:access_token] = access_token
    session[:user_name] = name
    user.access_token = access_token
    user.save
    redirect_to '/'
  end
  def destroy
    session.clear
    redirect_to root_url
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  protect_from_forgery except: :load
  def index
    @sites = Site.where( uid: session[:user_id] )
  end
  def edit
    @site = Site.find_by( uid: session[:user_id], id: params[:id] )
  end
  def new
    @site = Site.new
  end
  def show
    @site = Site.find_by( uid: session[:user_id], id: params[:id] )
    @sites = current_user && current_user.sites || []
  end
  def destroy
    @site = Site.find_by( uid: session[:user_id], id: params[:id] )
    @site.destroy
    redirect_to sites_path, :notice => "Deleted. #{undo_link}?"
  end
  def load
    @site = Site.where("domain = ? OR subdomain = ?", request.host, request.host).first
    if !@site
     render :html => 'Not Found', :layout => true
     return
    end
    begin
      @content = @site.content get_client( @site.creator.access_token ), request.env
    rescue Exception => err
      @content = err
    end
    respond_to do |format|
      format.all { render :html => @content, :layout => false }
    end
  end
  def create
    @site = Site.new site_params.merge( uid: session[:user_id] )
    @db = get_client @site.creator.access_token
    if @site.save
      begin
      @db.file_create_folder( @site.name )
      @db.put_file('/' + @site.name + '/index.html', open(Rails.public_path + 'welcome.html') )
      rescue
      end
      redirect_to @site
    else
      render :new
    end
  end
  def update
    @site = Site.find_by( uid: session[:user_id], id: params[:id] )
    if @site.update site_params.merge( uid: session[:user_id] )
      redirect_to @site
    else
      render :edit
    end
  end

  private
  def site_params
    params.require(:site).permit(:name, :domain)
  end
  def undo_link
    view_context.link_to("undo", revert_version_path(@site.versions.last), :method => :post)
  end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  def revert
    @version = PaperTrail::Version.find(params[:id])
    @version.reify.save
    redirect_to root_path
  end
end

app/controllers/webhook_controller.rb
class WebhookController < ApplicationController
  protect_from_forgery except: :post
  def challenge
    respond_to do |format|
      c =  params[:challenge]
      format.all { render :html => c, :layout => false }
    end
  end
  def post
    p params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>updog</title>
  <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
  <meta name="theme-color" content="#ffffff">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name='description'content='Free static site hosting, powered by DropBox'>
  <meta name='viewport' content='width=device-width'>
  <link rel="shortcut icon" href="/favicon.ico">
</head>
<body>
  <header>
  <div class='wrapper'>
  <h1><a href='/'><span>&#10145;</span> UpDog</a></h1>
  <nav>
  <a href='/about' class='active'>About</a>
  <a href='/source'>View Source</a>
  <a href='/pricing'>Pricing</a>
    <% if session[:user_name] %>
	<%= link_to 'Logout &nbsp;'.html_safe + session[:user_name], '/logout' %>
    <% else %>
      <a href='http://tyrant.gq/auth/dropbox'>Log in</a>
    <% end %>
  </nav>
</div>
</header>

<section class='main'>
    <%= yield %>
</section>


</body>
</html>

app/views/pages/about.html.erb
<div class='wrapper'>
  <h2>About</h2>
  <p>Updog is a static site host powered by the DropBox API.</p>

  <h2>Changelog</h2>
  <h3> 0.0.2 - 2015-02-24</h3>
  <h4>Added</h4>
  <ul>
    <li>Added support for custom domains</li>
  </ul>
  <h3> 0.0.1 - 2015-02-22</h3>
  <h4> Added</h4>
  <ul>
    <li> Static HTML support</li>
    <li>Added support for https:// subdomains</li>
    <li>Added support for Jekyll sites</li>
  </ul>

  <h2>Feedback</h2>
  <p>Is there a feature you’d like to see, or a bug you’d like to see fixed?</p>
  <p>Let me know by sending an email to <a href='mailto:tyrant@tyrant.ml'>tyrant@tyrant.ml</a>.</p>
</div>

app/views/pages/admin.html.erb
<div class='wrapper'>
  <h2>Admin</h2>
  <h3><%= @users.length %> total users.</h3>
  <ul>
  <% @users.each do |u| %>
    <li><%= u.name %> <small>(<%= u.email %>)</small></li>
  <% end %>
</ul>
  <h3><%= @sites.length %> total sites.</h3>
  <ul>
  <% @sites.each do |s| %>
    <li><%= link_to 'https://' + s.link, 'https://' + s.link %></li>
  <% end %>
  </ul>
</div>

app/views/pages/pricing.html.erb
<div class='wrapper'>
  <h2>Pricing</h2>
  <h1 class='js-fit'>Totally</h1>
  <h1 class='js-fit'>Freakin’</h1>
  <h1 class='js-fit'>Free.</h1>
</div>

app/views/pages/source.html.erb
<div class='wrapper'>
  <h2>View Source</h2>
  <p>In the spirit of open source, you can download this site’s source
  from <a href='https://github.com/jshawl/updog'>GitHub</a>.</p>
  <p>Updog is a Ruby on Rails application that interfaces with the
  DropBox API. This application converts requests to updog.co to DropBox,
  and sends back the result.</p>
  <p>In order to reduce my chances of hitting the DropBox API rate limits,
  requests to the API are cached for 30 seconds using memcached.</p>

  <p>Here are links to the more interesting parts of the code:</p>
  <ul>
    <li><a href='https://github.com/jshawl/updog/blob/master/app/controllers/sessions_controller.rb'>Log In with DropBox</a></li>
    <li><a href='https://github.com/jshawl/updog/blob/master/app/controllers/sites_controller.rb'>Create, edit, delete sites</a></li>
    <li><a href='https://github.com/jshawl/updog/blob/master/app/models/site.rb'>Load file from DropBox API</a></li>
  </ul>

</div>

app/views/sites/_form.html.erb
<% if @site.errors.any? %>
  <ul>
  <% @site.errors.full_messages.each do |e| %>
    <li> <%= e %></li>
  <% end %>
  </ul>
<% end %>
<%= form_for @site do |f| %>
  <%= f.label :name %>
  <div class='suffix-domain'>
    <%= f.text_field :name %>
  </div>
  <br>
  <%= f.label :domain %>
  <%= f.text_field :domain %> (optional) <small data-toggle=".instructions">What is this?</small><br><br>
  <%= f.submit 'Save', :class => 'btn-create' %>
  <div class='instructions'>
  <p>Using your own custom domain? To enable this feature:</p>
  <ol>
    <li>Log in to your DNS host.</li>
    <li>Create a new CNAME record that points to updog.co</li>
    <li>Save your changes and wait for the DNS to propagate.</li>
    <li>Need help? email <a href='mailto:tyrant@tyrant.ml'>jesse@updog.co</a></li>
  </ol>
  <p>Here’s what that process looks like on Digital Ocean:</p>
  <img src='https://dl.dropboxusercontent.com/s/'>
  </div>
  <br>
  <br>
<% end %>

app/views/sites/edit.html.erb
<div class='wrapper'>
  <h2>Edit <%= @site.name %></h2>
  <%= render 'form' %>
</div>

app/views/sites/index.html.erb
<% if session['access_token'] %>
  <div class='wrapper'>
    <% if notice %>
    <div class='notice'>
      <%=  notice.html_safe %>
    </div>
    <% end %>
      <div class='sites'>
	<% if @sites.length < 5 %>
	  <div class='cf'>
	    <div class='left'>
	      <a href='<%= new_site_path %>' class='site-new btn-create'><i class="fa fa-plus-circle"></i> Create New Site (<%= 5 - @sites.length %> left)</a>
	    </div>
	  </div>
	<% end %>
    <% if @sites.length != 0 %>
      <h2>Your Sites:</h2>
      <ul >
	<% @sites.each do |s| %>
	  <li class='cf'>

	  <div class='left'><%= link_to s.name, site_path( s ) %> </div> <div class='right'> <%= link_to 'Edit Site', edit_site_path( s ), :class => 'btn-edit' %> <%= link_to 'Delete Site', site_path( s ), :class=> 'btn-delete', method: :delete %> </div>
	  </li>
	<% end %>
      </ul>
    <% end %>
    </div>
  </div>

  <% else %>
    <div class='splash'>
      <div class='wrapper'>
    <h2>UpDog is a static website host, powered by DropBox</h2>
    </div>
  </div>

  <div class='wrapper'>
    <h3>How it works:</h3>
    <ol>
      <li><a href='/auth/dropbox'>Log In with Dropbox</a></li>
      <li>Create a new site</li>
      <li>Add your site to the newly created folder.</li>
      <li>Share your site.</li>
    </ol>
    <h3>What our customers are saying:</h3>
    <div class='table'>
      <div class='g-1-3'>
	<blockquote>It’s so fast!</blockquote>
      </div>
      <div class='g-1-3'>
	<blockquote>How does it update my site instantly? Magic?!</blockquote>
      </div>
      <div class='g-1-3'>
	<blockquote>What’s updog?</blockquote>
      </div>
      </div>
    </div>
  <% end %>

app/views/sites/load.css.erb
<%= @content %>

app/views/sites/load.html.erb
<%= @content %>

app/views/sites/new.html.erb
<div class='wrapper'>
  <h2>Create New Site</h2>
  <%= render 'form' %>
</div>

app/views/sites/show.html.erb
<div class='wrapper'>
  <div class='cf'>
  <div class='left'>
	<% if @sites.length < 5 %>
	  <a href='<%= new_site_path %>' class='site-new btn-create'><i class="fa fa-plus-circle"></i> Create New Site (<%= 5 - @sites.length %> left)</a>
	<% end %>
  </div>
  <div class='right'>
    <a href='<%= edit_site_path( @site ) %>' class='btn-edit'><i class="fa fa-pencil"></i> Edit</a>
<a data-method="delete" rel="nofollow" href='<%= site_path(@site) %>' class='btn-delete'><i class="fa fa-times"></i>
Delete </a>
</div>
</div>
<h2 class='site-title'><a href='//<%= @site.link %>'><%= @site.name %> <small><i class="fa fa-external-link"></i> </small></a></h2>  


  <small>Created at <time><%= @site.created_at.strftime("%B %d, %Y") %></time></small>

<br>

<h3>Instructions</h3>
<ol>
  <li>Add your site to your Dropbox folder in <strong>~/Dropbox/Apps/updog/<%= @site.name %></strong></li>
    <li><a href='//<%= @site.link %>'> View Site </a></li>
</ol>
</div>